export const shared = [
  'inline-flex',
  'justify-center',
  'items-center',
  'font-bold',
  'text-[13px]',
  'leading-[1.77]',
  'tracking-[1.6px]',
  'uppercase',
  'px-[15px]',
  'py-[10px]',
  'transition-all',
  'duration-200',
  'ease-cubic-in-out',
  'relative',
  'no-underline',
];

export const variants = {
  theme: {
    base: [],

    white: [
      'flex',
      'justify-center',
      'items-center',
      'rounded-lg',
      'h-[60px]',
      'bg-white',
      'text-[20px]',
      'leading-[1.15]',
      'text-[#222]',
      'shadow-[2px_2px_5px_rgba(0,0,0,0.35)]',
      'hover:text-secondary',
      'hover:-translate-y-0.5',
      'hover:shadow-[4px_4px_7px_rgba(0,0,0,0.15)]',
    ],

    gradient: [
      'relative',
      'flex',
      'w-[270px]',
      'rounded-full',
      'h-[60px]',
      'text-[20px]',
      'mx-auto',
      'mt-20',
      'border-4',
      'border-secondary',
      'text-secondary',
      'hover:bg-secondary',
      'hover:text-white',
      // Media query styles
      'md:text-lg',
      'md:h-12',
      'md:border-[3px]',
      'md:w-60',
    ],

    cta: [
      'bg-white',
      'text-brand',
      'w-[320px]',
      'h-[60px]',
      'rounded-[15px]',
      'text-[20px]',
      'mt-9',
      'shadow-[0px_8px_15px_rgba(0,0,0,0.13)]',
      '[backface-visibility:hidden]',
      'hover:shadow-[0px_10px_22px_rgba(0,0,0,0.1)]',
      'hover:scale-[1.01]',
      'hover:-translate-y-[3px]',
    ],

    brand: [
      'font-bold',
      'text-[20px]',
      'rounded-full',
      'py-5',
      'px-[50px]',
      'leading-none',
      'bg-brand',
      'text-white',
      'hover:bg-brand/90',
    ],

    secondary: [
      'relative',
      'h-[70px]',
      'rounded-full',
      'text-white',
      'text-[20px]',
      'font-bold',
      'uppercase',
      'tracking-[1px]',
      'px-[50px]',
      'py-3',
      'bg-[#1d81cc]',
      'transition-all',
      'duration-200',
      'ease-cubic-in-out',
      'overflow-hidden',
      'active:shadow-none',
    ],

    submit: [
      'relative',
      'h-[70px]',
      'rounded-full',
      'text-white',
      'uppercase',
      'tracking-[1px]',
      'bg-brand',
      'shadow-[0_0_10px_rgba(0,0,0,0.5)]',
      'hover:bg-brand/95',
      'active:shadow-none',
      'disabled:pointer-events-none',
      'disabled:cursor-not-allowed',
      '[&.js-trySend_.txt]:opacity-0',
      '[&.js-trySend_.lds-default]:opacity-100',
    ],

    'brand-outline': [
      'bg-transparent',
      'border-[3px]',
      'border-brand',
      'text-brand',
      'font-bold',
      'text-[20px]',
      'rounded-full',
      'py-5',
      'px-[50px]',
      'leading-none',
      'hover:bg-brand',
      'hover:text-white',
    ],
  },
};
